INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(1,'Norma'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(2,'Faber Castell'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(3,'Bic'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(4,'Kores'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(5,'Scribe'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(6,'Sharpie'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(7,'Canson'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(8,'Espiral'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(9,'Pointer'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(10,'Inpapeles'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(11,'Formas'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(12,'Minerva'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(13,'Mark inks'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(14,'Rairan'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(15,'Belpapel'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(16,'Formas Futuro'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(17,'Ecor distr.'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(18,'Primavera'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(19,'Happy'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(20,'Triton'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(21,'Schick'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(22,'Master AS'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(23,'Qnota'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(24,'Mercury'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(25,'Formas x'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(26,'Onix'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(27,'Offi-esco'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(28,'Pegastic'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(29,'Confetty'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(30,'Varta'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(31,'Energizer'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(32,'Medicare '); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(33,'Pelikan'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(34,'Make up'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(35,'Lander'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(36,'Eveready'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(37,'Tronex'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(38,'Mi trencito'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(39,'Mayfield'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(40,'Kilometrico'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(41,'Pelikan x'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(42,'Cellux'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(43,'Casio'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(44,'Varios'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(45,'Papeles'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(46,'Cartulinas'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(47,'Mostrador'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(48,'Carton Box'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(49,'Indust. Botero'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(50,'Scribe x'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(51,'Pappyer'); 
INSERT INTO `pos`.`mark`(`id`,`name`) VALUES(52,'Lukis'); 


INSERT INTO `pos`.`category`(`id`,`name`) VALUES(1,'Cuadernos'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(2,'Esferos'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(3,'Lapices'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(4,'Colores'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(5,'Plastilinas'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(6,'Pegantes'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(7,'Papeles'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(8,'Pinturas'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(9,'Bolsas regalo'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(10,'Fiestas'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(11,'Oficina'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(12,'Manualidades'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(13,'Varios'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(14,'Cartulinas'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(15,'Caja regalo'); 
INSERT INTO `pos`.`category`(`id`,`name`) VALUES(16,'Lienzos'); 
